# Site settings
title: silicak.es
email: iam@silicak.es
description: > # this means to ignore newlines until "baseurl:"
  A blog about code, philosophy, music and the world of front-end development
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.silicak.es" # the base hostname & protocol for your site
twitter_username: silicakes
github_username:  silicakes

# Build settings
markdown: kramdown
highlighter: pygments
